site_name: Alex's Home Assistant documentation
site_description: 'Compilation and reference of important home automation'
site_author: 'Alex van den Hoogen'
docs_dir: docs/
repo_name: 'alex3305/home-assistant-docs'
repo_url: 'https://github.com/alex3305/home-assistant-docs/'
nav:
  - Home: index.md
  - Installation: hardware/host-system.md
  - Add-ons:
    - InfluxDB: add-ons/influxdb.md

theme:
  name: 'material'
  palette:
    scheme: slate
    primary: light blue
    accent: teal
  icon:
    logo: material/home-heart

