site_name: Alex's Home Assistant documentation
site_description: 'Compilation and reference of important home automation'
site_author: 'Alex van den Hoogen'
docs_dir: docs/
repo_name: 'alex3305/home-assistant-docs'
repo_url: 'https://github.com/alex3305/home-assistant-docs/'
nav:
  - Home: index.md
  - Custom installation: hardware/host-system.md
  - Hardware:
    - IKEA TRADFRI open/close remote: hardware/ikea-tradfri-open-close-remote.md
  - Home Assistant:
    - HACS: home-assistant/hacs.md
  - Home Assistant Add-ons:
    - Bitwarden: add-ons/bitwarden.md
    - InfluxDB: 
      - Installation: add-ons/influxdb.md
      - Backup and restore: add-ons/influxdb-backup.md
      - Downsampling (RP/CQ): add-ons/influxdb-downsampling.md
  - Homelab:
    - Enabling QNAP disk spindown: homelab/qnap-disk-spindown.md
    - Mounting QNAP disks in Debian Linux: homelab/qnap-linux-mount.md
    - Plex QSV transcoding fix: homelab/plex-transcoding-fix.md

theme:
  name: 'material'
  palette:
    scheme: slate
    primary: light blue
    accent: teal
  icon:
    logo: material/home-heart
  features:
    - navigation.tabs

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
